name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['typescript']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3


  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install Node Modules
        run: npm i --include=dev

      - name: Run Build Test
        run: npm run build


  docs-test:
    name: Docs Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install Node Modules
        run: npm i --include=dev

      - name: Run Docs Test
        run: npm run docs


  lint-test:
    name: Lint Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install Node Modules
        run: npm i --include=dev

      - name: Run Lint Test
        run: npm run lint
